---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cluster-selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-ca-cert
  namespace: cert-manager
spec:
  duration: 17520h # 2years
  issuerRef:
    kind: Issuer
    name: cluster-selfsigned-issuer
  commonName: GATEWAYCA
  isCA: true
  secretName: gateway-ca-cert
  subject:
    organizations:
      - GATEWAYCA
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-cluster-issuer
spec:
  ca:
    secretName: gateway-ca-cert
---