###############################################################################
#
# © Copyright IBM Corp. 2023
#
###############################################################################
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
allowedFlexVolumes: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
kind: SecurityContextConstraints
metadata:
  name: ibm-ea-scc
priority: 0
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: MustRunAsRange
  uidRangeMax: 65534
  uidRangeMin: 5000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
groups: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret