apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: quick-start-ep
spec:
  license:
    accept: false
    license: ''
    use: EventAutomationNonProduction
  flink:
    endpoint: session-cluster-quick-start-rest:8081
  authoring:
    endpoints:
      - name: ui
        host: qs-ep-ui.<CLUSTER_HOST>
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
