# Copyright 2024 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

version: '3'

services:
  sp-flink:
    container_name: sp-flink
    image: "${SP_FLINK_IMAGE}"
    command: jobmanager
    ports:
      - 8081:8081
      - 6123:6123
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: sp-flink
      IBM_LICENSE_ACCEPT: "true"
      IBM_LICENSE_USE: "EventAutomationNonProduction"
      IBM_LICENSE_LICENSE: "L-AUKS-FKVXVL"
    volumes:
      - type: bind
        source: ..
        target: /var/host

  taskmanager:
    container_name: taskmanager
    image: "${SP_FLINK_IMAGE}"
    depends_on:
      - sp-flink
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: sp-flink
        taskmanager.numberOfTaskSlots: 20
        taskmanager.memory.process.size: 2G
        task.cancellation.timeout: 0
      IBM_LICENSE_ACCEPT: "true"
      IBM_LICENSE_USE: "EventAutomationNonProduction"
      IBM_LICENSE_LICENSE: "L-AUKS-FKVXVL"
    deploy:
      replicas: 1
