###############################################################################
#
# © Copyright IBM Corp. 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: replicated-topic
  labels:
    eventstreams.ibm.com/cluster: <cluster-name>
    backup.eventstreams.ibm.com/component: kafkatopic
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: '2'