apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: production-gw
  labels:
    backup.events.ibm.com/component: eventgateway
spec:
  license:
    accept: false
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationProduction
  manager:
    endpoint: 'https://<eem-manager-server-endpoint>/gateway'
    apiKey:
      secretName: <apikey-secret-name>
      key: apiKey
  listeners:
    - name: listener
      port: 8092
      tls:
        caSecret:
          secretName: <root-ca-secret-name>
      groups:
        - name: group
          type: EXPLICIT
          maxNumKafkaBrokers: 20
          endpoint:
            host: prod-gateway.<CLUSTER_HOST>
  gatewayGroupName: <gateway-group>
  gatewayID: <gateway-id>
