apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: production-gw
  labels:
    backup.events.ibm.com/component: eventgateway
spec:
  license:
    accept: false
    license: ""
    metric: ""
    use: ""
  endpoints:
    - name: gateway
      host: prod-gateway.<CLUSTER_HOST>
  managerEndpoint: https://<eem-manager-gateway-route>
  gatewayGroupName: <gateway-group>
  gatewayID: <gateway-id>
  tls:
    caSecretName: <root-ca-secret-name>