###############################################################################
#
# © Copyright IBM Corp. 2020, 2023
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: connect-prod
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
  labels:
    backup.eventstreams.ibm.com/component: kafkaconnect
spec:
  template:
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationProduction
          productID: 2cba508800504d0abfa48a0e2c4ecbe2
          productName: IBM Event Streams
          productVersion: EVENTSTREAMS_PRODUCT_VERSION
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: "All"
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          productCloudpakRatio: "1:1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - s390x
                      - ppc64le
  # bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - certificate: ca.crt
        # secretName: <eventstreams-instance>-cluster-ca-cert
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
