apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: non-prod
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  build:
    output:
      image: <registry>/my-org/my-connect-cluster-image:latest
      # pushSecret is used only when image is pushed to a protected image registry. 
      # This secret need to be created in same namespace that of the kafka connect. See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials for more information. 
      pushSecret: my-registry-credentials 
      type: docker
      plugins: 
        - name: connector1
          artifacts:
            - type: <type>
              url: <url>
              sha512sum: <sha512sum>
        - name: connector2
          artifacts:
            - type: <type>
              url: <url>
              sha512sum: <sha512sum>
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    pod:
      imagePullSecrets: # imagePullSecrets is used only when image is pushed to internal image resistry.
        - name: my-registry-credentials
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: EVENTSTREAMS_PRODUCT_VERSION
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: <ADD-NAME-OF-KAFKA-CONNECT-CR>-connect
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          productCloudpakRatio: "2:1"
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
#  tls:
#    trustedCertificates:
#      - secretName: quickstart-cluster-ca-cert
#        certificate: ca.crt
#  authentication:
#    type: scram-sha-512
#    username: my-connect-user
#    passwordSecret:
#      secretName: my-connect-user
#      password: my-connect-password-key