apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: ubp-gw
  labels:
    backup.events.ibm.com/component: eventgateway
spec:
  license:
    accept: false
    license: ''
    metric: MONTHLY_API_CALL
    use: CloudPakForIntegrationProduction
  managerEndpoint: https://<eem-manager-gateway-route>
  gatewayGroupName: <gateway-group>
  gatewayID: <gateway-id>
  tls:
    caSecretName: <root-ca-secret-name>