apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: ubp-gw
  labels:
    backup.events.ibm.com/component: eventgateway
spec:
  license:
    accept: false
    license: 'L-QXEH-527JUB'
    metric: MONTHLY_API_CALL
    use: CloudPakForIntegrationProduction
  manager:
    endpoint: 'https://<eem-manager-server-endpoint>/gateway'
    apiKey:
      secretName: <apikey-secret-name>
      key: apiKey
  listeners:
    - name: listener
      port: 8092
      tls:
        caSecret:
          secretName: <root-ca-secret-name>
      groups:
        - name: group
          type: EXPLICIT
          maxNumKafkaBrokers: 20
  gatewayGroupName: <gateway-group>
  gatewayID: <gateway-id>
