---
apiVersion: v1
kind: Secret
metadata:
  name: operator-certificate-password
  namespace: <flink-operator-namespace>
type: Opaque
data:
  password: <Base64 encoded password>
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flink-operator-cert
  namespace: <flink-operator-namespace>
spec:
  dnsNames:
    - '*.flink.svc'
    - '*.svc.cluster.local'
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: operator-certificate-password
        key: password
  issuerRef:
    kind: ClusterIssuer
    name: ea-cluster-issuer
  commonName: FlinkOperator
  secretName: flink-operator-cert
---