---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cluster-selfsigned-issuer
  namespace: <cert-manager-namespace>
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ea-ca-cert
  namespace: <cert-manager-namespace>
spec:
  duration: 17520h # 2years
  issuerRef:
    kind: Issuer
    name: cluster-selfsigned-issuer
  commonName: EACA
  isCA: true
  secretName: ea-ca-cert
  subject:
    organizations:
      - IBM EA
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ea-cluster-issuer
spec:
  ca:
    secretName: ea-ca-cert
---