###############################################################################
#
# © Copyright IBM Corp. 2020, 2023
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
# This kafka user generates SCRAM-SHA-512 credentials for a consumer application.
# It grants permissions to consume from topic testtopic1 only, and from consumer group testgroup1 only.
# It also grants permission to read schema testschema1 only.
metadata:
  name: consumer-scram-testtopic1-testgroup1-testschema1
  namespace: placeholder
  labels:
    eventstreams.ibm.com/cluster: <cluster name>
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: testtopic1
          patternType: literal
        operations:
          - Read
      - resource:
          type: group
          name: testgroup1
          patternType: literal
        operations:
          - Read
      - resource:
          type: topic
          name: __schema_testschema1
          patternType: literal
        operations:
          - Read
