###############################################################################
#
# © Copyright IBM Corp. 2020, 2023
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
# This kafka user generates Mutual TLS credentials for a producer application.
# It grants permissions to produce to topic testtopic1 only.
# It also grants permission to read schema testschema1 only.
metadata:
  name: producer-tls-testtopic1-testschema1
  namespace: placeholder
  labels:
    eventstreams.ibm.com/cluster: <cluster name>
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: testtopic1
          patternType: literal
        operations:
          - Write
      - resource:
          type: topic
          name: __schema_testschema1
          patternType: literal
        operations:
          - Read
