###############################################################################
#
# © Copyright IBM Corp. 2020, 2023
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
# This kafka user generates Mutual TLS credentials for a producer application.
# It grants permissions to produce any topic.
# It also grants permission to read any schema.
metadata:
  name: producer-tls-all-topics
  namespace: placeholder
  labels:
    eventstreams.ibm.com/cluster: <cluster name>
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations:
          - Read
