apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: quick-start-manager
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: false
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    endpoints:
      - name: ui
        host: qs-eem-ui.<CLUSTER_HOST>
      - name: gateway
        host: qs-eem-gateway.<CLUSTER_HOST>
      - name: admin
        host: qs-eem-admin.<CLUSTER_HOST>
      - name: server
        host: eem.qs-eem-server.<CLUSTER_HOST>
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi
