apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: apic-integration
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: false
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    endpoints:
      - name: ui
        host: qs-eem-ui.<CLUSTER_HOST>
      - name: gateway
        host: qs-eem-gateway.<CLUSTER_HOST>
      - name: admin
        host: qs-eem-admin.<CLUSTER_HOST>
      - name: apic
        host: qs-apic.<CLUSTER_HOST>
      - name: server
        host: eem.qs-eem-server.<CLUSTER_HOST>
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: <name of secret containing the ca.crt of your API Connect instance, required if using a different CA to EEM>
    apic:
      tls: false
      clientSubjectDN: <common-name>
      jwks:
        endpoint: <end point>
