apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: apic-integration
spec:
  license:
    accept: false
    license: ""
    metric: ""
    use: ""
  manager:
    endpoints:
      - name: ui
        host: qs-eem-ui.<CLUSTER_HOST>
      - name: gateway
        host: qs-eem-gateway.<CLUSTER_HOST>
      - name: admin
        host: qs-eem-admin.<CLUSTER_HOST>
      - name: apic
        host: qs-apic.<CLUSTER_HOST>
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    apic:
      tls: false
      clientSubjectDN: <common-name>
      jwks:
        endpoint: <end point>
