apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  flinkEnvironment: ${FLINK_ENV}
  image: ${APP_IMAGE}
  imagePullPolicy: Always
  flinkVersion: v2_1
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: '2'
    table.exec.source.idle-timeout: '30 s'
    execution.checkpointing.interval: '5000'
    execution.checkpointing.unaligned.enabled: 'false'
    state.backend.type: rocksdb
    state.backend.rocksdb.thread.num: '10'
    execution.checkpointing.incremental: 'true'
    state.backend.rocksdb.use-bloom-filter: 'true'
    execution.checkpointing.dir: 'file:///opt/flink/volume/flink-cp'
    execution.checkpointing.num-retained: '3'
    execution.checkpointing.savepoint-dir: 'file:///opt/flink/volume/flink-sp'
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-volume
              mountPath: /opt/flink/volume
            - name: flow-volume
              mountPath: /opt/flink/ibm-flow/flow.sql
              subPath: flow.sql
              readOnly: true
      volumes:
        - name: flink-volume
          persistentVolumeClaim:
            claimName: ${PVC_NAME}
        - name: flow-volume
          secret:
            secretName: ${APP_NAME}
  jobManager:
    resource:
      memory: '2048m'
      cpu: 1
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
            imagePullPolicy: Always
  taskManager:
    resource:
      memory: '2048m'
      cpu: 2
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
            imagePullPolicy: Always
  job:
    jarURI: local:///opt/flink/usrlib/sql-runner.jar
    args: ["/opt/flink/ibm-flow/flow.sql"]
    state: running
    parallelism: 1
    upgradeMode: ${UPGRADE_MODE}
    initialSavepointPath: ${SAVEPOINT_PATH}
  cmfRestClassRef:
    name: ${CMF_REST_CLASS}
    namespace: ${CMF_REST_CLASS_NS}
