# {
#   "description": "Suitable for small workloads with minimal High Availability (i.e. flink jobs are restarted automatically on job manager restart but there is a single job manager). To enable job manager High Availability, set the configuration parameter spec.jobManager.replicas to a value greater than 1. Accept the license agreement https://ibm.biz/ea-license by setting the configuration parameter license.accept to 'true'; otherwise the deployment fails. This sample uses a PersistentVolumeClaim (PVC), thus there are manual prerequisites for deploying the PVC. For details, see https://ibm.biz/ep-installing-flink",
#   "name": "Minimal production"
# }
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: session-cluster-minimal-prod
spec:
  flinkConfiguration:
    license.use: ""
    license.license: ""
    license.accept: ""
    high-availability.type: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: 'file:///opt/flink/volume/flink-ha'
    restart-strategy: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: '10'
    restart-strategy.failure-rate.failure-rate-interval: '10 min'
    restart-strategy.failure-rate.delay: '30 s'
    execution.checkpointing.interval: '5000'
    execution.checkpointing.unaligned: 'false'
    state.backend.type: rocksdb
    state.backend.incremental: 'true'
    state.backend.rocksdb.use-bloom-filter: 'true'
    state.checkpoints.dir: 'file:///opt/flink/volume/flink-cp'
    state.checkpoints.num-retained: '3'
    state.savepoints.dir: 'file:///opt/flink/volume/flink-sp'
    taskmanager.numberOfTaskSlots: '10'
    table.exec.source.idle-timeout: '30 s'
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
            - name: flink-volume
              mountPath: /opt/flink/volume
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: flink-volume
          persistentVolumeClaim:
            claimName: ibm-flink-pvc
  jobManager:
    replicas: 1
    resource:
      memory: '2048m'
      cpu: 0.25
  taskManager:
    resource:
      memory: '2048m'
      cpu: 1
  mode: native