
# {
#   "description": "Quick start sample without persistent storage. Suitable for tiny workloads that do not require reliability. Accept the license agreement https://ibm.biz/ea-license by setting the configuration parameter license.accept to 'true'; otherwise the deployment fails. For details, see https://ibm.biz/ep-installing-flink",
#   "name": "Quick start"
# }
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: session-cluster-quick-start
spec:
  flinkConfiguration:
    license.use: EventAutomationNonProduction
    license.license: L-HRZF-DWHH7A
    license.accept: 'false'
    execution.checkpointing.interval: '5000'
    state.backend.type: rocksdb
    state.checkpoints.num-retained: '3'
    taskmanager.numberOfTaskSlots: '4'
    table.exec.source.idle-timeout: '30 s'
    restart-strategy: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: '5'
    restart-strategy.failure-rate.failure-rate-interval: '5 min'
    restart-strategy.failure-rate.delay: '30 s'
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
      volumes:
        - name: flink-logs
          emptyDir: {}
  jobManager:
    resource:
      memory: '2048m'
      cpu: 0.5
  taskManager:
    resource:
      memory: '2048m'
      cpu: 0.5
  mode: native