###############################################################################
#
# © Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: development
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: false
    license: "L-HRZF-DWHH7A"
    use: "EventAutomationNonProduction"
  adminApi: {}
  adminUI:
    authentication:
      - type: integrationKeycloak
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 3
      authorization:
        type: simple
      config:
        inter.broker.protocol.version: "3.7"
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: development-metrics-config
      storage:
        type: ephemeral
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: development-metrics-config
      storage:
        type: ephemeral
