###############################################################################
#
# © Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: light-insecure
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: false
    license: "L-AUKS-FKVXVL"
    use: "EventAutomationNonProduction"
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  security:
    internalTls: NONE
  strimziOverrides:
    kafka:
      config:
        inter.broker.protocol.version: "3.9"
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
        auto.create.topics.enable: 'false'
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: light-insecure-metrics-config
    zookeeper:
      replicas: 1
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: light-insecure-metrics-config
      storage:
        type: ephemeral
    nodePools:
      - name: kafka
        replicas: 1
        storage:
          type: ephemeral
        roles:
          - broker
