###############################################################################
#
# Licensed Materials - Property of IBM
#
# IBM Event Streams
#
# (C) Copyright IBM Corp. 2020, 2023  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: light-insecure
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/es-license
    accept: false
    license: ""
    use: ""
  adminApi: {}
  adminUI:
    authentication:
      - type: scram-sha-512
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        containerPort: 3000
        class: <INGRESS-CLASS>
  apicurioRegistry: {}
  restProducer: {}
  collector: {}
  security:
    internalTls: NONE
  strimziOverrides:
    kafka:
      replicas: 1
      config:
        inter.broker.protocol.version: "3.4"
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: light-insecure-metrics-config
      storage:
        type: ephemeral
    zookeeper:
      replicas: 1
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: light-insecure-metrics-config
      storage:
        type: ephemeral
