###############################################################################
#
# © Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: prod-9-brokers
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: false
    license: "L-CYBH-K48BZQ"
    use: "EventAutomationProduction"
  adminApi:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME>
        class: <INGRESS-CLASS>
        containerPort: 8001
  adminUI:
    authentication:
      - type: scram-sha-512
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 3000
  apicurioRegistry:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 8002
  collector: {}
  restProducer:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 8003
  strimziOverrides:
    kafka:
      authorization:
        type: simple
      config:
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 9
        default.replication.factor: 3
        min.insync.replicas: 2
        auto.create.topics.enable: 'false'
      listeners:
        - name: external
          port: 9094
          type: ingress
          tls: true
          authentication:
            type: scram-sha-512
          configuration:
            bootstrap:
              host: <HOSTNAME/IP-ADDRESS>
            hostTemplate: broker-{nodeId}.<HOSTNAME/IP-ADDRESS>
            class: <INGRESS-CLASS>
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: prod-9-brokers-metrics-config
    nodePools:
      - name: kafka
        replicas: 9
        storage:
          type: persistent-claim
          size: 2Gi
          class: ''
        roles:
          - broker
        resources:
          requests:
            memory: 8096Mi
            cpu: 2000m
          limits:
            memory: 8096Mi
            cpu: 2000m
      - name: controller
        replicas: 3
        storage:
          type: persistent-claim
          size: 4Gi
          class: ''
        roles:
          - controller