apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: production-manager
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: false
    license: 'L-KCVZ-JL5CRM'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationProduction
  manager:
    authConfig:
      authType: OIDC
      oidcConfig:
        clientIDKey: <client-id>
        clientSecretKey: <client-secret>
        discovery: true
        secretName: <keycloak-oidc-secret>
        site: 'https://<keycloak-route>/realms/<keycloak-realm>'
    tls:
      caSecretName: <custom-root-ca>
      ui:
        secretName: <custom-ui-cert>
      trustedCertificates:
        - certificate: <ca-key>
          secretName: <keycloak-ca>
    storage:
      storageClassName: <storage-class>
      type: persistent-claim
