apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: apic-integration
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: false
    license: ''
    metric: ''
    use: ''
  manager:
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    apic:
      tls: false
      clientSubjectDN: <common-name>
      jwks:
        endpoint: <end point>