apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: production-ep
spec:
  license:
    accept: false
    license: 'L-CYBH-K48BZQ'
    use: EventAutomationProduction
  flink:
    endpoint: session-cluster-prod-rest:8081
    tls:
      secretName: <jks-truststore-secret>
      secretKeyRef:
        name: <truststore-password-secret>
        key: <key-containing-password>
  authoring:
    storage:
      type: persistent-claim
      storageClassName: <storage-class>
    authConfig:
      authType: OIDC
      oidcConfig:
        clientIDKey: <client-id>
        clientSecretKey: <client-secret>
        discovery: true
        secretName: <keycloak-oidc-secret>
        site: 'https://<keycloak-route>/realms/<keycloak-realm>'
    tls:
      caSecretName: <custom-root-ca>
      ui:
        secretName: <custom-ui-cert>
      trustedCertificates:
        - certificate: <ca-key>
          secretName: <keycloak-ca>
