apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: quick-start-ep
spec:
  license:
    accept: false
    license: 'L-KCVZ-JL5CRM'
    use: EventAutomationNonProduction
  flink:
    endpoint: session-cluster-quick-start-rest:8081
  authoring:
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
