apiVersion: flink.apache.org/v1beta1
kind: FlinkStateSnapshot
metadata:
  name: application-cluster-prod-checkpoint
spec:
  backoffLimit: 1
  jobReference:
    kind: FlinkDeployment
    name: application-cluster-prod
  checkpoint: {}
