{
 "title": "IBM Event Streams - Geo-replication",
 "tags": [
  "Kafka",
  "Kafka Mirror Maker 2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "kubernetes_namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "eventstreams_cluster_name",
    "label": "Cluster Name",
    "query": "label_values(kube_pod_labels{namespace=\"$kubernetes_namespace\"}, label_eventstreams_ibm_com_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "description": "Shows the total number of connectors running in this connect cluster.\n\nEach geo-replictor pairing has two connectors - the MirrorSourceConnector and the MirrorCheckpointConnector.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"})"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "description": "Shows the total number of connect tasks for this geo-replicator",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"})"
    }
   ]
  },
  {
   "title": "Running Geo-replication Tasks",
   "type": "singlestat",
   "description": "Shows the total number of MirrorSourceConnector tasks for this geo-replicator",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\",connector=~\".*MirrorSourceConnector.*\"})"
    }
   ]
  },
  {
   "title": "Paused Geo-replication Tasks",
   "type": "singlestat",
   "description": "Shows the total number of paused MirrorSourceConnector tasks for this geo-replicator",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\",connector=~\".*MirrorSourceConnector.*\"})"
    }
   ]
  },
  {
   "title": "Running Checkpointing Tasks",
   "type": "singlestat",
   "description": "Shows the total number of running MirrorCheckpointConnector tasks for this geo-replicator",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\",connector=~\".*MirrorCheckpointConnector.*\"})"
    }
   ]
  },
  {
   "title": "Paused Checkpointing Tasks",
   "type": "singlestat",
   "description": "Shows the total number of paused MirrorCheckpointConnector tasks for this geo-replicator",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\",status=\"paused\",connector=~\".*MirrorCheckpointConnector.*\"})"
    }
   ]
  },
  { "title": "Geo-replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Geo-replicated Records per Topic",
   "type": "graph",
   "description": "Shows the rate of geo-replicated data in records per second, for each replicated topic",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Records / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_MirrorSourceConnector_record_rate{eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Geo-replicated Bytes per Topic",
   "type": "graph",
   "description": "Shows the rate of geo-replicated data in bytes per second, , for each replicated topic",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Bytes / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_MirrorSourceConnector_byte_rate{eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Geo-replicated Record Age per Topic Partition",
   "type": "graph",
   "description": "Shows the age of each record when consumed by the geo-replicator ",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_mirror_MirrorSourceConnector_record_age_ms{eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Geo-replication Latency per Topic Partition",
   "type": "graph",
   "description": "Shows the  times in ms between each record's timestamp and the acknowledgement at the destination cluster",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_mirror_MirrorSourceConnector_replication_latency_ms{eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  { "title": "Consumer group checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Consumer Group Checkpoint Latency per Topic",
   "type": "graph",
   "description": "Shows the time in ms between the consumer group commit at the origin, and the acknowledgement at the destination cluster for the checkpoint",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_MirrorCheckpointConnector_latency_ms{eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Geo-replication workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "description": "Memory usage of the KafkaMirrorMaker2 pods used for geo-replication",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "description": "Time spend in garbage collection by the KafkaMirrorMaker2 pods used for geo-replication",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{eventstreams_ibm_com_kind=~\"KafkaMirrorMaker2\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",job=\"kubernetes-pods\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}