{
 "title": "IBM Event Streams Performance Dashboard",
 "description": "Stats relating to the performance of Event Streams pods",
 "tags": [ "Event Streams" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "clusterName",
    "label": "Cluster Name",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, label_eventstreams_ibm_com_cluster)"
   },
   {
    "name": "esOperator",
    "label": "Event Streams Operator",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "adminApi",
    "label": "Admin APi",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_app_kubernetes_io_instance=~\"$clusterName\"}, pod)"
   },
   {
    "name": "recordApi",
    "label": "Record API",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_app_kubernetes_io_instance=~\"$clusterName\"}, pod)"
   },
   {
    "name": "schema",
    "label": "Schema Registry",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_app_kubernetes_io_instance=~\"$clusterName\"}, pod)"
   },
   {
    "name": "collector",
    "label": "Metrics Collector",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_app_kubernetes_io_instance=~\"$clusterName\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Streams Pod Status for $clusterName",
   "type": "graph",
   "description": "Monitors the Event Streams pod status for a specific release to see if there are any pods that are unready or ready. Useful to determine the health of a release.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"clusterName.*|$esOperator\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"$namespace\", pod=~\"clusterName.*|$esOperator\"}) by(phase)",
     "legendFormat": "Unready"
    }
   ]
  },
  {
   "title": "CS Pod Status",
   "type": "graph",
   "description": "IBM Event Streams relies on some of the functionality provided by pods in IBM Common Services. This monitors the Common Services pod health to ensure that they are healthy.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"ibm-common-services\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"ibm-common-services\", condition=\"false\"})",
     "legendFormat": "Unready"
    }
   ]
  },
  {
   "title": "Event Streams Cluster Operator Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU Usage for $esOperator",
   "type": "singlestat",
   "description": "The Event Streams Cluster Operator is the controller of the Event Streams deployment. It is responsible for managing and deploying all Event Streams components. This tracks the current CPU usage of the Event Streams Operator. ",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "repeat": "esOperator",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$esOperator\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU usage and Limit for $esOperator",
   "type": "graph",
   "description": "The Event Streams Cluster Operator is the controller of the Event Streams deployment. It is responsible for managing and deploying all Event Streams components. This tracks the current CPU usage and limit of the Event Streams Operator. ",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
   "repeat": "esOperator",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\",container_name!=\"POD\",pod=~\"$esOperator\"}[2m] ) ",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$esOperator\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage for $esOperator",
   "type": "singlestat",
   "description": "The Event Streams Cluster Operator is the controller of the Event Streams deployment. It is responsible for managing and deploying all Event Streams components. This tracks the current Memory usage of the Event Streams Operator. ",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "repeat": "esOperator",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod=~\"$esOperator\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Memory Usage and Limit for $esOperator",
   "type": "graph",
   "description": "The Event Streams Cluster Operator is the controller of the Event Streams deployment. It is responsible for managing and deploying all Event Streams components. This tracks the current memory usage and limit of the Event Streams Operator. ",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 17 },
   "repeat": "esOperator",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\", pod=~\"$esOperator\", container_name!=\"POD\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$esOperator\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Admin API Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Bytes Rate In and Out for $adminApi",
   "type": "graph",
   "description": "Admin API is an important component of Event Streams as it allows users to perform administrative tasks on their Kafka Brokers. There are many messages going into and out of Admin API. This tracks the bytes going in and out of Admin API.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "repeat": "adminApi",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$adminApi\",interface=\"eth0\"}[2m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$collector\",interface=\"eth0\"}[2m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "CPU Usage for $adminApi",
   "type": "singlestat",
   "description": "Admin API is an important component of Event Streams as it allows users to perform administrative tasks on their Kafka Brokers. There are many messages going into and out of Admin API. This tracks the current CPU usage of Admin API.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 32 },
   "repeat": "adminApi",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$adminApi\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU and Limit for $adminApi",
   "type": "graph",
   "description": "Admin API is an important component of Event Streams as it allows users to perform administrative tasks on their Kafka Brokers. There are many messages going into and out of Admin API. This tracks the current CPU usage and memory limit of Admin API.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 32 },
   "repeat": "adminApi",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod=~\"$adminApi\"}[2m] ) )",
     "legendFormat": "Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$adminApi\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage for $adminApi",
   "type": "singlestat",
   "description": "Admin API is an important component of Event Streams as it allows users to perform administrative tasks on their Kafka Brokers. There are many messages going into and out of Admin API. This tracks the current memory usage of Admin API.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 39 },
   "repeat": "adminApi",
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod=~\"$adminApi\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Memory Usage and Limit for $adminApi",
   "type": "graph",
   "description": "Admin API is an important component of Event Streams as it allows users to perform administrative tasks on their Kafka Brokers. There are many messages going into and out of Admin API. This tracks the current memory usage and limit of Admin API.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 39 },
   "repeat": "adminApi",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod=~\"$adminApi\", container_name!=\"POD\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$adminApi\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Schema Registry Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total CPU Usage for $schema",
   "type": "singlestat",
   "description": "Schema Registry stores the schemas that producers will use to produce a structured message to Kafka. Many components connect to Schema Registry for information about schemas. This tracks the CPU usage of Schema Registry.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 47 },
   "repeat": "schema",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$schema\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU Usage and Limit for $schema",
   "type": "graph",
   "description": "Schema Registry stores the schemas that producers will use to produce a structured message to Kafka. Many components connect to Schema Registry for information about schemas. This tracks the CPU usage and limit of the Schema Registry pod.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 47 },
   "repeat": "schema",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\",container_name!=\"POD\",pod=~\"$schema\"}[2m] ) )",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$schema\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Current Memory for $schema",
   "type": "singlestat",
   "description": "Schema Registry stores the schemas that producers will use to produce a structured message to Kafka. Many components connect to Schema Registry for information about schemas. This tracks the memory usage of the Schema Registry pod.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 54 },
   "repeat": "schema",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod=~\"$schema\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Memory Usage for $schema",
   "type": "graph",
   "description": "Schema Registry stores the schemas that producers will use to produce a structured message to Kafka. Many components connect to Schema Registry for information about schemas. This tracks the memory usage and limit of the Schema Registry pod.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 54 },
   "repeat": "schema",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\", pod=~\"$schema\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$schema\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  { "title": "Record API Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Byte Rates In and Out for $recordApi",
   "type": "graph",
   "description": "Record API can be used to produce messages to Kafka without have to construct a producer. Many messages are sent in and out of Record API. This tracks the bytes going in and out of Record API.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "repeat": "recordApi",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$recordApi\",interface=\"eth0\"}[2m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$recordApi\",interface=\"eth0\"}[2m])",
     "legendFormat": "Transmitted "
    }
   ]
  },
  {
   "title": "Memory Usage for $recordApi",
   "type": "singlestat",
   "description": "Record API can be used to produce messages to Kafka without have to construct a producer. Many messages are sent in and out of Record API. This tracks the current memory usage of Record API.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
   "repeat": "recordApi",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod=~\"$recordApi\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "CPU usage and limit for $recordApi",
   "type": "graph",
   "description": "Record API can be used to produce messages to Kafka without have to construct a producer. Many messages are sent in and out of Record API. This tracks the current CPU usage and CPU limit of Record API.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 69 },
   "repeat": "recordApi",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod=~\"$recordApi\"}[2m] )",
     "legendFormat": "Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$recordApi\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage for $recordApi",
   "type": "singlestat",
   "description": "Record API can be used to produce messages to Kafka without have to construct a producer. Many messages are sent in and out of Record API. This tracks the current CPU usage of Record API.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 76 },
   "repeat": "recordApi",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$recordApi\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "Memory Usage for $recordApi",
   "type": "graph",
   "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage and limits of Kafka proxy $proxy",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 76 },
   "repeat": "recordApi",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod=~\"$recordApi\", container_name!=\"POD\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$recordApi\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Collector Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Byte Rate In and Out for $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the byte rate into and out of the collector",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "repeat": "collector",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$collector\",interface=\"eth0\"}[2m])",
     "legendFormat": "RX : {{ pod_name }}"
    },
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$collector\",interface=\"eth0\"}[2m])",
     "legendFormat": "TX : {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage for $collector",
   "type": "singlestat",
   "description": "The metrics collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the total memory usage of the collector.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 91 },
   "repeat": "collector",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod=~\"$collector\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "CPU for $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the CPU usage and limit of the metrics collector.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 91 },
   "repeat": "collector",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod=~\"$collector\"}[2m] ) )",
     "legendFormat": "Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$collector\", container!=\"POD\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU for $collector",
   "type": "singlestat",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the total CPU usage of the collector as a sum of the containers",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 98 },
   "repeat": "collector",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$collector\"}[2m])) "
    }
   ]
  },
  {
   "title": "Memory Usage for $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the memory usage  and limit of the collectors containers.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 98 },
   "repeat": "collector",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod=~\"$collector\", container_name!=\"POD\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$collector\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  }
 ]
}